---
- name: Install Zend Debugger dependencies
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - libssl0.9.8
  notify: Restart Apache

- name: Download Zend Debugger
  sudo: yes
  script: zend.sh {{ liara_temp_dir }} creates={{ liara_php_mod_dir }}/ZendDebugger.so

- name: Configure Zend Debugger
  sudo: yes
  ini_file: option={{item.option}} value={{item.value}} section=zenddebugger dest={{ liara_php_conf_dir }}/zend.ini
  with_items:
    - { option: zend_extension, value: "{{ liara_php_mod_dir }}/ZendDebugger.so" }
    - { option: zend_debugger.allow_hosts, value: "0.0.0.0/0" }
    - { option: zend_debugger.expose_remotely, value: always }
